Use memset() instead of bzero()
- The function bzero() is deprecated (marked as LEGACY in POSIX.1-2001)
  use memset() in new programs. POSIX.1-2008 removes the specification
  of bzero(). From: https://linux.die.net/man/3/bzero
- Furthermore, this fixes the compiler warning using MinGW-w64:
  pcsensor.c:272:5: warning: implicit declaration of function 'bzero'
  [-Wimplicit-function-declaration] bzero(answer, reqIntLen);